Issue63/feliks
reTeaming/rehome pull request #109
Opened 2023-07-17 13:06 UTC by FeliksMarksen

closes #63 

Die Übungsseite wurde erstellt mit Suchleiste, Detailansicht und weiteren Funktionen. 
## UI 
### Suchleiste 
Die Suchleiste zeigt in zwei ausklappbaren Panels jeweils die Übungen und die Übungsblöcke. Man kann hier  

- Nach Übungen und Blöcken suchen 
- Übungen und Blöcke auswählen woraufhin die Detailansicht angezeigt wird
- Suchinhalt löschen 

### Detailansicht Übungsblock
Die Detailansicht der Übungsblöcke besteht aus dem Namen des Block und dessen Übungen. Man kann hier 

- die einzelnen Übungen aufrufen und zu den jeweiligen Detailansichten wechseln.

### Detailansicht Übung 
Die Detailansicht der Übungen besteht aus dem Namen und der ID der `DefaultExercises`. Man kann hier

- über einen `FloatingActionButton` die Übung zu einem Block hinzufügen. Hierfür öffnet sich ein PopUp indem die aktuellen Blöcke angezeigt werden.  Dort können ebenfalls über ein eigenes PopUp auch neue Blöcke erstellt werden. 
- nach dem Hinzufügen der Übung zu einem Block erscheint eine kurze Benachrichtigung 
- Wenn man von einem Block auf diese Wechselt, kann man über ein Pfeil-Icon zu diesem wieder zurückkehren 

## Bloc Logik 

### `ExerciseSearchBar` Bloc 
Die Logik für die Suchleiste besteht aus dem `ExerciseSearchBloc` und dem `ExBlockSearchBloc` diese sind dem `PatientSearchBloc` sehr ähnlich, nur wurde Parameter für den zu suchenden Inhalt an die jeweilige Anwendung angepasst. 

### `DefaultExerciseBloc`
Dieser beeinhaltet alles was es brauch, um eine Übung oder einen Block aufzurufen. Hier wird also gesteuert was in der Detailansicht angezeigt wird. Dabei gibt es für die einzelnen Fälle der Navigation eigene Events und Funktionen.

2023-07-17 15:51 UTC, LenaHaggi requested changes
Bis auf die kleinen Änderungen top. Volle Funktionalität trotz der zum Teil sehr verschachtelten Struktur. Besonders schön durchdacht ist das Feedback, wenn man eine Exercise zu einem Block hinzufügt. Nachdem alles an unser Theme angepasst wird und das Backend steht, ist die Übungsseite komplett. Tolle Arbeit!

2023-07-17 15:51 UTC, LenaHaggi commented on lib/presentation/exercise_page.dart
> +      final List<ListTile> listTiles =
Hier wäre ein TODO fürs Backend noch gut.

2023-07-17 15:51 UTC, LenaHaggi commented on lib/business_logic/default_exercise/default_exercise_bloc.dart
> +        event.activeExblock, null, ActiveExState.activeExercise));
hier müsste in dem DefaultExerciseState von emit ActiveExState.activeExblock anstatt ActiveExState.activeExercise stehen

2023-07-17 15:51 UTC, LenaHaggi commented on lib/presentation/exercise_page.dart
> +            child: Text("ID:${activeExercise!.id}")),
Hier würde ich ein Leerzeichen noch empfehlen nach dem ID:

2023-07-17 15:54 UTC, LenaHaggi approved these changes
Jetzt passt alles!

2023-07-19 12:35 UTC, felixmattersberger requested changes
Bitte die Merge-Konflikte noch beheben, ansonsten passt alles :-)

2023-07-19 13:59 UTC, felixmattersberger approved these changes

2023-07-19 13:59 UTC, merged