Update + Create von Patienten
reTeaming/rehome pull request #128
Opened 2023-07-21 15:11 UTC by leonfuss

Schließt #117 

Ein Patient mit all seinen verschachtelten Attributen kann geupdate / erstellt werden. In dem die Methode `updateOrCreatePatient(Patient patient)`aufgerufen wird. Dieses baut rekursiv einen Parse-Baum aus aus `ParseObject`s aus allen im Patienten enthaltenen Klassen. Anschließen werden diese alle mit ihren Feldern, Pointern und Relationen in der Datenbank gespeichert. 

Um den Patienten und all sein Subjekte richtig zu identifizieren wird die `objectId` der einzelnen Felder verglichen. Sollte diese verändert werden, resultiert dass in einem neuen Objekt in der Datenbank. Sollte keine `objectId` in einem Objekt angegeben sein, wird dieses automatisch neu erstellt.

2023-07-22 11:40 UTC, Borajiin commented on lib/domain/models/patient/exercise.dart
> +  const ParameterSet(this.name, this.repetition, this.objectId, this.type);
schöne Umsetzung zum Speichern des Types

2023-07-22 15:52 UTC, Borajiin requested changes
Alles in allem eine sehr schöne und sinnvolle Umsetzung. Ich habe noch ein paar Sachen anzumerken:
- Die Klasse **ExerciseBlock** wird in manchen Referenzen mit ExerciseBloc (ohne k) geschrieben. Um eine Verwechslung mit den Flutter Blocs auszuschließen und das gesamt ein wenig zu vereinheitlichen, habe ich unten einige Stellen markiert, in denen mir aufgefallen ist, dass das k ausgelassen wurde.
- speichern der objectId beim abrufen (teilweise schon gemacht z.b goals)
- Die **Auslagerungen** der einzelnen Klassen aus der Homework Datei sind sehr sinvoll, allerdings wäre es meiner Meinung nach angebracht, die jeweils relevanten Klassen/Enums mit auszulagern. Sonst muss man unnötiger Weise die Klassen aus anderen Dateien verwenden.
- Da die **ObjectId null** sein kann, sollte hier eventuell in irgendeiner Weise eine Prüfung stattfinden. Ansonsten könnte es sein das das Erstellen mit back4app nicht funktioniert.
- In einigen ParseObjekt implementierenden Klassen wurde die Variablen der Keys umbenannt von `key... ` zu `_key...`. Allerdings wurden einige Klassen ausgelassen. Hat dies einen Grund? 
- Die **Auslagerung der Imports** in die models Dateien erscheint mir sehr sinvoll: Gut gemacht! Allerdings wird diese Datei häufig nicht benutzt, sondern die alten Imports werden immer noch verwendet. Dies sollte ausgebessert werden
- Beim **Abrufen der Objekte** wird bislang die ObjectId nicht gespeichert, was dazu führt, das abgerufene Objekte nicht geupdated werden können. Bei Updaten sollte eine ObjectId mitgegeben werden, da sonst ein neues Objekt erstellt wird. Da diese aber nicht gespeichert wird, kann sie auch nicht zum updaten mitgegeben werden

Ich habe alle Stellen zu den obigen Problemen, welche mir aufgefallen sind, unten markiert.

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_jerk.dart
> +import 'package:rehome/domain/models/patient/exercise.dart';
Hier könnten neue models Dateien verwendet werden

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_jerk.dart
> +      ..objectId = objectId
Null-Prüfung evtl. erforderlich

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_parameterset.dart
> +      ..objectId = objectId
Null-Prüfung evtl. erforderlich

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_parameterset.dart
> +      ..achievedAt = achievedAt;
Null-Prüfung evtl. erforderlich

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_rangeofmotion.dart
> +      ..objectId = objectId
Null-Prüfung evtl. erforderlich

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_weekhomework.dart
> +    }
die Variablen wurden hier exerciseBloc... genannt und nicht ExerciseBloc**k**...

2023-07-22 15:52 UTC, Borajiin commented on lib/data/models/parse_patient.dart
> +      ..objectId = objectId
Null-Prüfung evtl. erforderlich

2023-07-22 18:26 UTC, leonfuss commented
Im Generellen ist die Null-Prüfung der ObjectId bei `toParse` nicht notwendig. Sollte diese `null` sein, wird automatisch ein neues Object erstellt. Ich werde dementsprechend alle dementsprechenden Markierungen als resolved markieren.

2023-07-22 18:36 UTC, leonfuss commented on lib/domain/models/patient/week_homework.dart
> +      return mockweekhomework; // TODO: null oder mock?
Das wird nochmal in #130 geändert.

2023-07-22 18:44 UTC, leonfuss commented on lib/domain/models/patient/exercise_bloc.dart
> +        exerciseBlock.name, block, exerciseBlock.status.toBlockStatus());
Das wurde eindeutig übersehen

2023-07-22 19:04 UTC, leonfuss commented
Bis jetzt wurden nur den Keys, die einen Konflikt in der `models.dart` Datei erzeugt haben das Prefix "_" hinzugefügt.
Da diese Variablen dann privat sind, können sie nicht mehr miteinander in Konflikt geraten. Der Einheitlichkeit halber habe ich alle Keys die nicht im Konflikt stehen auch umbenannt. Alle restlichen Punkte wurden auch umgesetzt. Insbesondere die Verwendung der `models.dart` Dateien wurde in noch mehr Daten angewendet

2023-07-23 08:21 UTC, Borajiin requested changes
Alle geforderten Änderungen wurde soweit sehr gut umgesetzt. 
Allerdings wurde das Enum Day nicht in WeekHomework sondern in ExerciseBlock verschoben. 
Außerdem wurden die ObjectIds bislang nur bei den Goals beim Abrufen hinzugefügt. Gibt es einen Grund dafür?

2023-07-23 08:21 UTC, Borajiin commented on lib/domain/models/patient/exercise_block.dart
> +enum Day { monday, tuesday, wednesday, thursday, friday, saturday, sunday }
Enum sollte in WeekHomework sein, da die ExerciseBlock Klasse keinen Tag speichet.

2023-07-26 07:46 UTC, leonfuss commented on lib/domain/models/patient/exercise_block.dart
> +enum Day { monday, tuesday, wednesday, thursday, friday, saturday, sunday }
Das Enum verschiebe ich noch

2023-07-26 07:47 UTC, leonfuss commented
Die ObjectIds wurden noch nicht bei jedem geändert, da das die Quintessenz des PullRequest #128 ist. Dort wurde das unteranderem für alle Objekte vorgenommen

2023-07-26 08:25 UTC, Borajiin approved these changes
Jetzt passt alles, perfekt!

2023-07-26 08:25 UTC, merged