Pop-up window for exercise parameters
reTeaming/rehome pull request #140
Opened 2023-07-28 08:29 UTC by Benzhen-W

2023-07-28 08:48 UTC, Benzhen-W commented
Noch nicht mit dem Backend verbunden

2023-07-30 07:38 UTC, felixmattersberger requested changes
Super Arbeit! 
Bitte nur noch die Kommentare in Zeile 342+343 löschen :-)

2023-07-30 07:38 UTC, felixmattersberger commented on lib/presentation/patient_page.dart
> +            // test
Kannst du diese Kommentare vielleicht noch aus dem Code entfernen?

2023-07-30 08:25 UTC, Benzhen-W commented on lib/presentation/patient_page.dart
> +            // test
Jetzt habe ich den Kommentar entfernt.

2023-07-30 09:26 UTC, felixmattersberger approved these changes
Super, passt :-)

2023-07-30 09:26 UTC, merged