Issue15/bene - backend Anbindung zum Authentifizieren (und Registrieren) von Nutzern (Therapeuten)
reTeaming/rehome pull request #26
Opened 2023-06-10 16:54 UTC by Borajiin

schließt #15 

Backend Anbindung zur Authentifizierung von Nutzern wurde erstellt. 
Hierfür wurden zunächst:
- Parser initialisiert, um ein Abrufen und Speichern mit der 'Back4App' -  Anwendung zu ermöglichen (zurzeit wird diese Initialisierung in main.dart aufgerufen, kann bei Bedarf aber verschoben werden)
- Nutzer-Registrierung erstellt, um das Erstellen von neuen Nutzern zu erleichtern (nur für Entwicklungsprozess)
- Nutzer-Authentifizierung erstellt, um übergeben Nutzernamen und Passwörter mit der Datenbank in 'Back4App' abzugleichen

Die Authentifizierung wird in auth_repository.dart aufgerufen und es werden Nutzername und Passwort übergeben (aus Login-Page-Feldern). Die authUser Funktion der Klasse UserAuth in backend_login.dart gleicht durch eine backend-Anbindung den Nutzernamen und das Passwort ab und übergibt true, im Falle einer erfolgreichen Authentifizierung, oder false, im Falle einer fehlgeschlagenen Authentifizierung (z.B. falsches Passwort oder Benutzername).

2023-06-10 17:00 UTC, Borajiin commented
Ich hätte noch Diskussionsbedarf bezüglich der Passwort-Speicherung: 
Die Überlegung war ja ursprünglich, das Passwort für Sicherheitsgründe nur als Hash zu speichern/abzurufen.
Ich hab das bisher allerdings noch nicht umgesetzt, da die Speicherung in Back4App schon automatisch verborgen/verschlüsselt gespeichert wird (siehe User in Back4App-Dashboard) und daher meiner Meinung eine zusätzliche Hash-Speicherung nicht unbedingt nötig ist. 
Bei Bedarf kann ich das noch umsetzen, ich wollte aber zunächst mal nachfragen ob es überhaupt notwendig ist.

2023-06-12 08:55 UTC, leonfuss requested changes
Sehr schöne Implementierung. Ist der User damit auch im Backend automatische eingeloggt oder müssen wir bei jedem nächsten Request die Nutzerdaten wieder mitschicken ?

2023-06-12 08:55 UTC, leonfuss commented on lib/data/backend_init.dart
> +    WidgetsFlutterBinding.ensureInitialized();
`WidgetsFlutterBindung.ensureInitialized()` sollte noch in `main.dart` aufgerufen werden. Wenn wir später mehrere unterschiedliche initialisierungen haben, wird es sonst bisschen unübersichtlich welche wir als erstes Aufrufen müssen damit alles passt :)

2023-06-12 08:55 UTC, leonfuss commented on lib/data/backend_init.dart
> +
Wir müssen uns noch ein paar Gedanken über api-keys machen. Eine direkte öffentliche Speicherung auf Github, wie hier ist eindeutig nicht ideal. Jeder der dieses Projekt sieht, kann die keys einfach übernehmen und sachen nach belieben auf dem Server ändern. Evtl. ist eine seperate Datei, die im `.gitignore` steht und dann geparsed wird eine Lösung

2023-06-15 21:12 UTC, Borajiin commented on lib/data/backend_init.dart
> +
Wurde jetzt durch separate Datei gelöst, die mit .gitignore verborgen wird.
Ich habe bislang keine Möglichkeit gefunden die Keys noch einmal zu ändern, sodass hier keine richtigen Keys mehr im Klartext stehen. Das muss wahrscheinlich noch ausgebessert werden.

2023-06-15 21:13 UTC, Borajiin commented on lib/data/backend_init.dart
> +    WidgetsFlutterBinding.ensureInitialized();
ensureInitialized wird jetzt in main aufgerufen

2023-06-18 14:55 UTC, leonfuss approved these changes
Super! Danke das du die Änderungswünsche so schön umgesetzt hast

2023-06-18 14:56 UTC, merged