Issue19/lena
reTeaming/rehome pull request #28
Opened 2023-06-15 11:48 UTC by LenaHaggi

Betrifft:

#19 

Patientenseite, welche die Hausaufgaben, Ziele und mögliche Übungen anzeigen soll.

2023-06-15 12:25 UTC, leonfuss commented on lib/app.dart
Diese Seite sollte nicht auf main gemerged werden. Es sollen nur die Seiten hinzugefügt werden, aber nicht das Routing vom Standart Verhalten abgeändert werden. Fürs testen ist das natürlich notwendig, danach aber nicht zielführend.

2023-06-20 11:20 UTC, leonfuss submitted a review, later dismissed

2023-07-07 11:27 UTC, FeliksMarksen requested changes
Was toll ist: 
Starten funktioniert, Anzeigen sieht gut aus und auch die ausklappbaren Menüs funktionieren gut mit den anderen Widgets. Auch schön gelöst mit dem Logo.  Sehr gute Code Qualität mit schönem Refactoring der einzelnen Widgets. Auch die Bloc Logik sieht top aus. 

Was noch verbessert werden sollte: 
Das Widget für die Übungen bekommt bei unterschiedlichen Größen des Tablets einen PixelOverflow. (Wenn wir nur für die eine Tabletgröße entwickeln, kann man das natürlich ignorieren) 
Kleinigkeit: Hier und da ein paar mehr Comments bzgl der Widget Wahl. 

 
Was man vielleicht ändern könnte: 
Design mäßig könnte man dem  ausklappbaren Tile der Aktiven Ziele, unter dem die vergangen Ziele sind, noch eine Änderung geben, so dass klar ist wo man die vergangen Ziele findet. 

(Beim Mergen auf Backend_init und Backendkeys achten, dass die nicht mitkommen. )

2023-07-09 15:43 UTC, leonfuss approved these changes

2023-07-09 15:44 UTC, merged