theme.dart hinzugefügt, basic ThemeData implementiert
reTeaming/rehome pull request #39
Opened 2023-06-20 15:43 UTC by felixmattersberger

2023-06-24 14:06 UTC, FeliksMarksen submitted a review, later dismissed
Sieht top aus!
Schön übersichtlich und umfassend.

2023-06-25 17:34 UTC, leonfuss requested changes
Sehr schönes Refactoring. Aktuell fehlt nur noch die Verknüpfung  zum Material Theme. 
Das heißt das Theme muss in unseren Widget Tree in der MaterialApp eingefügt werden, damit es einen Effekt auf die gesamte App hat.

2023-06-30 09:54 UTC, Borajiin approved these changes
Schönes Theme. Passt soweit alles.

2023-07-01 19:23 UTC, leonfuss requested changes
Bis die eine Unklarheit ist alles supi. 

Bitte den Code oben erklären oder entsprechend anpassen :)

2023-07-01 19:23 UTC, leonfuss commented on lib/app.dart
> +              .copyWith(primary: const Color(0xFF2E2E48))),
Warum wird die passende Farbe nicht direkt im Colorscheme eingebracht?

2023-07-06 07:48 UTC, felixmattersberger commented on lib/app.dart
> +              .copyWith(primary: const Color(0xFF2E2E48))),
https://github.com/reTeaming/rehome/pull/39/commits/355f9ef95fbe3f3fb5b61555bb51dab896288db5

so besser ?:-)

2023-07-07 08:13 UTC, leonfuss approved these changes
Träumchen

2023-07-07 08:13 UTC, merged