Settings page with logout function(resubmit)
reTeaming/rehome pull request #53
Opened 2023-06-27 18:18 UTC by Benzhen-W

#32 
Ich habe die PR #47  erneut eingereicht, 
nun werden die Userinformationen korrekt angezeigt, ebenso die Abmeldefunktion.

2023-06-28 05:45 UTC, leonfuss requested changes
Bitte lasse `dart format .` laufen. Commite die dann vorhandenen Änderungen und pushe erneute auf `issue32/benzhen`

2023-06-28 07:27 UTC, Benzhen-W commented
Entschuldigung, ich habe es vergessen, ich habe es jetzt geändert und erneut eingereicht.

2023-07-07 12:55 UTC, leonfuss commented
@Benzhen-W hat alle anderforderungen an den Task erfüllt. Das Frontend funktioniert ohne Probleme

Aktuell wird wenn versucht wird die Institution zu ändern eine Exception geworfen und die Daten im Backend nicht upgedated.

@Borajiin du hast da vermutlich mehr Einblicke als ich. Willst du einmal drüber schauen?
Bis dahin kann der PullRequest nicht gemerged werden.

```[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'List<ParseObject>' is not a subtype of type 'ParseObject'
#0      UserBackend.updateBackendInstitution (package:rehome/data/backend_user.dart:54:7)<asynchronous suspension>
#1      UserRepository.updateInstitution (package:rehome/domain/repositories/user_repository.dart:48:9)<asynchronous suspension>

2023-07-09 10:00 UTC, Borajiin requested changes
Die markierte Funktion sollte entfernt werde, damit ein erzwungener Change ausgeschlossen werden kann.

2023-07-09 15:01 UTC, leonfuss approved these changes
Jetzt ist es ein Träumchen

2023-07-09 15:03 UTC, Borajiin approved these changes
Funktion wurde entfernt, und alles läuft weiterhin. Perfekt!

2023-07-09 15:05 UTC, merged