Patienten abrufen vom Backend ohne Hausaufgaben
reTeaming/rehome pull request #78
Opened 2023-07-10 15:30 UTC by leonfuss

2023-07-10 17:12 UTC, Borajiin requested changes
Schöne Implementierung. 
Ich habe noch ein paar Sachen markiert, welche noch gut wären zu ändern. Hauptsächlich sollten ein paar Variablen und Funktionsnamen angepasst werden.
Ansonsten passt alles soweit

2023-07-10 17:12 UTC, Borajiin commented on lib/domain/models/patient/patient.dart
> -        therapyStart,
Sollte nicht gelöscht werden

2023-07-10 17:17 UTC, leonfuss commented on lib/domain/models/patient/patient.dart
> +  final DateTime? therapyStart;
therapyStart ist im Backend nicht als required gesetzt. Damit deshalb keine Konvertierungsfehler auftreten ist es auch nullable

2023-07-10 17:20 UTC, leonfuss commented
Die Änderungen wurden alle Umgesetzt

2023-07-10 17:26 UTC, Borajiin requested changes
Nochmal eine kleine Anpassung, der Rest wurde gut umgesetzt.

2023-07-10 17:26 UTC, Borajiin commented on lib/data/models/parse_patient.dart
> +      super.removeRelation(keyGoals, exercise);
die Funktionsnamen sollten hier auch angepasst werden auf addExerciseDefaultData

2023-07-10 17:35 UTC, Borajiin requested changes
Hier sollte nochmal eine kleine Änderung von Nöten sein.

2023-07-10 17:35 UTC, Borajiin commented on lib/data/models/parse_goal.dart
> +const String keyGoal = "goal";
Der Key sollte groß geschrieben werden, da sonst die Klasse nicht gefunden wird.

2023-07-11 11:40 UTC, leonfuss commented on lib/data/models/parse_goal.dart
> +const String keyGoal = "goal";
Interessanter Weise scheint es kein Problem beim Abrufen zu geben. Der Konsistenz halber habe ich es trotzdem geändern.

2023-07-11 19:02 UTC, Borajiin approved these changes
Perfekt! Jetzt sieht alles richtig aus.

2023-07-11 19:03 UTC, merged